pull_request_rules:
  - name: Automatic merge for dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build
    actions:
      merge:
        method: merge
  - name: Automatic merge for PartTimeLegend
    conditions:
      - author=PartTimeLegend
      - check-success=build
    actions:
      merge:
        method: merge